[package]
name = "convert_world"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fastnbt = "2.4.4"
fastanvil = "0.30.0"
serde = { version = "1.0.195", features = ["derive"] }
bit_field = "0.10.2"
flume = "0.11.0"
threadpool = "1.8.1"
hashbrown = "0.14.3"
rayon = "1.8.1"

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
strip = "symbols"
